service: onboarding-serverless
frameworkVersion: '3'
useDotenv: true

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    layer: true

provider:
  name: aws
  region: us-west-1
  runtime: python3.8
  logs:
    httpApi: true

functions:
  api:
    handler: wsgi_handler.handler
    layers:
      - Ref: PythonRequirementsLambdaLayer
      - arn:aws:lambda:us-west-1:898466741470:layer:psycopg2-py38:1
    events:
      - httpApi: '*'
plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-dotenv-plugin